# iCluster+ model tuning

library(minfi)
library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
library(iClusterPlus)

## RNAseq

rna_data <- read.table("/mnt/petasan_ccb/alessandro/SCANB/rna_logtransformed.tsv", header=TRUE, sep="\t", row.names=1)
# Feature selection
gene_mads <- apply(rna_data, 1, mad)
ordered_mads <- order(gene_mads, decreasing = TRUE)
top_3000_indices <- ordered_mads[1:3000]
rna_data <- rna_data[top_3000_indices, ]
rna_matrix <- as.matrix(rna_data)
#Transpose
rna_mat <- t(rna_matrix)

## Mehtylation

adjusted_data <- readRDS("/mnt/petasan_ccb/alessandro/SCANB/adjusted_data.rds")

# Filtering
library(minfi)
library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
#library(sesameData)
ann <- getAnnotation(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
keep_autosomes <- !(ann$chr %in% c("chrX", "chrY"))
keep_cpg <- grepl("^cg", ann$Name)
probes_to_keep <- ann$Name[keep_autosomes & keep_cpg]
probes_filtered <- adjusted_data[rownames(adjusted_data) %in% probes_to_keep, ]
met_filtered <- as.matrix(probes_filtered)

# Enhancers results
enhancers_pairs <- readRDS("/mnt/petasan_ccb/alessandro/SCANB/result_pairs_enhancer.rds")
en_pairs <- enhancers_pairs[order(enhancers_pairs$Pe), ]
top_pairs_en <- en_pairs[en_pairs$Raw.p < 1e-9, ]
top_cpg_en <- unique(top_pairs_en$Probe)

# Promoters results
promoters_pairs <- readRDS("/mnt/petasan_ccb/alessandro/SCANB/result_pairs_promoter.rds")
pr_pairs <- promoters_pairs[order(promoters_pairs$Pe), ]
top_pairs_pr <- pr_pairs[pr_pairs$Raw.p < 1e-9, ]
top_cpg_pr <- unique(top_pairs_pr$Probe)

# Final data
top_cpg_combined <- union(top_cpg_en, top_cpg_pr)
met_matrix_filtered <- met_filtered[rownames(met_filtered) %in% top_cpg_combined, ]

met_mvals <- met_matrix_filtered
# to prevent ±Infinity errors
met_mvals[met_mvals == 0] <- 0.001
met_mvals[met_mvals == 1] <- 0.999
# logit transformation to get M-values
met_mvals <- log2(met_mvals / (1 - met_mvals))
#transpose
meth_mat <- t(met_mvals)


## CNV

dna_matrix_filtered <- read.csv("/mnt/petasan_ccb/alessandro/SCANB/dna_matrix_filtered_2900genes.csv", header = TRUE)
cnv_log_ratio <- dna_matrix_filtered
# homozygous deletions (0 alleles) to avoid log2(0) = -Inf
cnv_log_ratio[cnv_log_ratio == 0] <- 0.5  
#log2 scale
cnv_log_ratio <- log2(cnv_log_ratio / 2)
cnv_mat <- t(cnv_log_ratio)

#order samples
common_samples <- intersect(intersect(rownames(rna_mat), rownames(meth_mat)), rownames(cnv_mat))
rna_aligned  <- rna_mat[common_samples, ]
meth_aligned <- meth_mat[common_samples, ]
cnv_aligned  <- cnv_mat[common_samples, ]

# Z-score standardization across features (columns) ensures equal variance weight

rna_scaled  <- scale(rna_aligned, center = TRUE, scale = TRUE)
meth_scaled <- scale(meth_aligned, center = TRUE, scale = TRUE)
cnv_scaled  <- scale(cnv_aligned, center = TRUE, scale = TRUE)

#replace any NaNs generated by zero-variance columns
rna_scaled[is.na(rna_scaled)]   <- 0
meth_scaled[is.na(meth_scaled)] <- 0
cnv_scaled[is.na(cnv_scaled)]   <- 0



# iCluster+

set.seed(123) #seed for reproducibility

# Tuning the Icluster2b model to find optimal k and lambda
# Run the tuning loop across a range of K latent variables (Clusters = K + 1)
for(k in 1:5){
  cat("Starting model tuning for K =", k, "at", as.character(Sys.time()), "\n")
  
  cv.fit <- tune.iClusterPlus(
    cpus = 16, # Matches the cluster cores in .sh
    dt1 = rna_scaled, 
    dt2 = meth_scaled, 
    dt3 = cnv_scaled,
    type = c("gaussian", "gaussian", "gaussian"), 
    K = k, 
    n.lambda = 185,                              
    scale.lambda = c(1, 1, 1), #datasets already manually Z-scored 
    maxiter = 20
  )
  
  #saves each K 
  output_path <- paste0("/mnt/petasan_ccb/alessandro/SCANB/", "cv_fit_k", k, ".rds")
  saveRDS(cv.fit, file = output_path)
  
  cat("Finished and saved K =", k, "to", output_path, "\n\n")
}
