# Fits a single iClusterPlus model (fixed K, fixed lambda) on a subsample
# (without replacement) of the full cohort. Intended to be launched once per
# SLURM array task, with SLURM_ARRAY_TASK_ID used both as the iteration ID
# and as the RNG seed for reproducible subsampling.
#
# Usage (called automatically by the sbatch script below):
#   Rscript run_icluster_bootstrap.R <iter_id> <subsample_fraction> <outdir>

# Data loading

library(minfi)
library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
library(iClusterPlus)

## RNAseq

rna_data <- read.table("/mnt/petasan_ccb/alessandro/SCANB/rna_logtransformed.tsv", header=TRUE, sep="\t", row.names=1)
# Feature selection
gene_mads <- apply(rna_data, 1, mad)
ordered_mads <- order(gene_mads, decreasing = TRUE)
top_3000_indices <- ordered_mads[1:3000]
rna_data <- rna_data[top_3000_indices, ]
rna_matrix <- as.matrix(rna_data)
#Transpose
rna_mat <- t(rna_matrix)

## Mehtylation

adjusted_data <- readRDS("/mnt/petasan_ccb/alessandro/SCANB/adjusted_data.rds")

# Filtering
library(minfi)
library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
#library(sesameData)
ann <- getAnnotation(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
keep_autosomes <- !(ann$chr %in% c("chrX", "chrY"))
keep_cpg <- grepl("^cg", ann$Name)
probes_to_keep <- ann$Name[keep_autosomes & keep_cpg]
probes_filtered <- adjusted_data[rownames(adjusted_data) %in% probes_to_keep, ]
met_filtered <- as.matrix(probes_filtered)

# Enhancers results
enhancers_pairs <- readRDS("/mnt/petasan_ccb/alessandro/SCANB/result_pairs_enhancer.rds")
en_pairs <- enhancers_pairs[order(enhancers_pairs$Pe), ]
top_pairs_en <- en_pairs[en_pairs$Raw.p < 1e-9, ]
top_cpg_en <- unique(top_pairs_en$Probe)

# Promoters results
promoters_pairs <- readRDS("/mnt/petasan_ccb/alessandro/SCANB/result_pairs_promoter.rds")
pr_pairs <- promoters_pairs[order(promoters_pairs$Pe), ]
top_pairs_pr <- pr_pairs[pr_pairs$Raw.p < 1e-9, ]
top_cpg_pr <- unique(top_pairs_pr$Probe)

# Final data
top_cpg_combined <- union(top_cpg_en, top_cpg_pr)
met_matrix_filtered <- met_filtered[rownames(met_filtered) %in% top_cpg_combined, ]

met_mvals <- met_matrix_filtered
# to prevent ±Infinity errors
met_mvals[met_mvals == 0] <- 0.001
met_mvals[met_mvals == 1] <- 0.999
# logit transformation to get M-values
met_mvals <- log2(met_mvals / (1 - met_mvals))
#transpose
meth_mat <- t(met_mvals)


## CNV

dna_matrix_filtered <- read.csv("/mnt/petasan_ccb/alessandro/SCANB/dna_matrix_filtered_2900genes.csv", header = TRUE, row.names = 1)
cnv_log_ratio <- dna_matrix_filtered
# homozygous deletions (0 alleles) to avoid log2(0) = -Inf
cnv_log_ratio[cnv_log_ratio == 0] <- 0.5  
#log2 scale
cnv_log_ratio <- log2(cnv_log_ratio / 2)
cnv_mat <- t(cnv_log_ratio)

#order samples
common_samples <- intersect(intersect(rownames(rna_mat), rownames(meth_mat)), rownames(cnv_mat))
rna_aligned  <- rna_mat[common_samples, ]
meth_aligned <- meth_mat[common_samples, ]
cnv_aligned  <- cnv_mat[common_samples, ]

# Z-score standardization across features (columns) ensures equal variance weight

rna_scaled  <- scale(rna_aligned, center = TRUE, scale = TRUE)
meth_scaled <- scale(meth_aligned, center = TRUE, scale = TRUE)
cnv_scaled  <- scale(cnv_aligned, center = TRUE, scale = TRUE)

#replace any NaNs generated by zero-variance columns
rna_scaled[is.na(rna_scaled)]   <- 0
meth_scaled[is.na(meth_scaled)] <- 0
cnv_scaled[is.na(cnv_scaled)]   <- 0

n_total <- nrow(rna_scaled)
stopifnot(nrow(meth_scaled) == n_total, nrow(cnv_scaled) == n_total)



## ---- 1. Parse arguments -----------------------------------------------
args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 3) {
  stop("Usage: Rscript run_icluster_bootstrap.R <iter_id> <subsample_fraction> <outdir>")
}

iter_id     <- as.integer(args[1])   # e.g. SLURM_ARRAY_TASK_ID, used as seed too
frac        <- as.numeric(args[2])   # e.g. 0.8 for 80% subsampling
outdir      <- args[3]

dir.create(outdir, showWarnings = FALSE, recursive = TRUE)

cat("Iteration:", iter_id, "| Subsample fraction:", frac, "| Outdir:", outdir, "\n")
cat("Start time:", as.character(Sys.time()), "\n")



## ---- 3. Load the fixed K / lambda chosen from tuning --------------------
# From your tuning step: K = 3 (i.e. output[[2]], 3-cluster solution),
# lambda = the row of output[[2]]$lambda that minimized BIC (minBICid[2]).
# Save these once from your tuning session, e.g.:
#   saveRDS(list(K = 3, lambda = output[[2]]$lambda[minBICid[2], ]),
#           file = "chosen_model_params.rds")
model_params <- readRDS("chosen_model_params.rds")
K      <- model_params$K
lambda <- model_params$lambda

cat("Using K =", K, "| lambda =", paste(round(lambda, 4), collapse = ", "), "\n")

## Subsample without replacement 
set.seed(iter_id)  # reproducible: each array task gets its own, fixed seed
n_sub <- floor(frac * n_total)
sub_idx <- sample(seq_len(n_total), size = n_sub, replace = FALSE)

rna_sub  <- rna_scaled[sub_idx, , drop = FALSE]
meth_sub <- meth_scaled[sub_idx, , drop = FALSE]
cnv_sub  <- cnv_scaled[sub_idx, , drop = FALSE]

sample_ids_sub <- rownames(rna_scaled)[sub_idx]

## ---- 5. Fit iClusterPlus at fixed K / lambda ----------------------------
fit <- iClusterPlus(
  dt1 = rna_sub,
  dt2 = meth_sub,
  dt3 = cnv_sub,
  type = c("gaussian", "gaussian", "gaussian"),
  K = K,
  lambda = lambda,
  maxiter = 20
)

## ---- 6. Save outputs ------------------------------------------------------
result <- list(
  iter_id        = iter_id,
  sub_idx        = sub_idx,
  sample_ids     = sample_ids_sub,
  cluster        = fit$clusters,
  meanZ          = fit$meanZ,
  K              = K,
  lambda         = lambda
)

saveRDS(result, file = file.path(outdir, paste0("icluster_boot_", iter_id, ".rds")))

cat("End time:", as.character(Sys.time()), "\n")
cat("Done.\n")
