# iCluster+ model tuning

library(minfi)
library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
library(iClusterPlus)

## RNAseq

rna_data <- read.table("/mnt/petasan_ccb/alessandro/SCANB/rna_logtransformed.tsv", header=TRUE, sep="\t", row.names=1)
# Feature selection
gene_mads <- apply(rna_data, 1, mad)
ordered_mads <- order(gene_mads, decreasing = TRUE)
top_3000_indices <- ordered_mads[1:3000]
rna_data <- rna_data[top_3000_indices, ]
rna_matrix <- as.matrix(rna_data)
#Transpose
rna_mat <- t(rna_matrix)

## Mehtylation

adjusted_data <- readRDS("/mnt/petasan_ccb/alessandro/SCANB/adjusted_data.rds")

# Filtering
library(minfi)
library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
#library(sesameData)
ann <- getAnnotation(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
keep_autosomes <- !(ann$chr %in% c("chrX", "chrY"))
keep_cpg <- grepl("^cg", ann$Name)
probes_to_keep <- ann$Name[keep_autosomes & keep_cpg]
probes_filtered <- adjusted_data[rownames(adjusted_data) %in% probes_to_keep, ]
met_filtered <- as.matrix(probes_filtered)

# Enhancers results
enhancers_pairs <- readRDS("/mnt/petasan_ccb/alessandro/SCANB/result_pairs_enhancer.rds")
en_pairs <- enhancers_pairs[order(enhancers_pairs$Pe), ]
top_pairs_en <- en_pairs[en_pairs$Raw.p < 1e-9, ]
top_cpg_en <- unique(top_pairs_en$Probe)

# Promoters results
promoters_pairs <- readRDS("/mnt/petasan_ccb/alessandro/SCANB/result_pairs_promoter.rds")
pr_pairs <- promoters_pairs[order(promoters_pairs$Pe), ]
top_pairs_pr <- pr_pairs[pr_pairs$Raw.p < 1e-9, ]
top_cpg_pr <- unique(top_pairs_pr$Probe)

# Final data
top_cpg_combined <- union(top_cpg_en, top_cpg_pr)
met_matrix_filtered <- met_filtered[rownames(met_filtered) %in% top_cpg_combined, ]

met_mvals <- met_matrix_filtered
# to prevent ±Infinity errors
met_mvals[met_mvals == 0] <- 0.001
met_mvals[met_mvals == 1] <- 0.999
# logit transformation to get M-values
met_mvals <- log2(met_mvals / (1 - met_mvals))
#transpose
meth_mat <- t(met_mvals)


## CNV

dna_matrix_filtered <- read.csv("/mnt/petasan_ccb/alessandro/SCANB/dna_matrix_filtered_2900genes.csv", header = TRUE)
cnv_log_ratio <- dna_matrix_filtered
# homozygous deletions (0 alleles) to avoid log2(0) = -Inf
cnv_log_ratio[cnv_log_ratio == 0] <- 0.5  
#log2 scale
cnv_log_ratio <- log2(cnv_log_ratio / 2)
cnv_mat <- t(cnv_log_ratio)

#order samples
common_samples <- intersect(intersect(rownames(rna_mat), rownames(meth_mat)), rownames(cnv_mat))
rna_aligned  <- rna_mat[common_samples, ]
meth_aligned <- meth_mat[common_samples, ]
cnv_aligned  <- cnv_mat[common_samples, ]

# Z-score standardization across features (columns) ensures equal variance weight

rna_scaled  <- scale(rna_aligned, center = TRUE, scale = TRUE)
meth_scaled <- scale(meth_aligned, center = TRUE, scale = TRUE)
cnv_scaled  <- scale(cnv_aligned, center = TRUE, scale = TRUE)

#replace any NaNs generated by zero-variance columns
rna_scaled[is.na(rna_scaled)]   <- 0
meth_scaled[is.na(meth_scaled)] <- 0
cnv_scaled[is.na(cnv_scaled)]   <- 0



# iCluster Bayes

set.seed(123) 
cat("Starting Bayesian model tuning at", as.character(Sys.time()), "\n")

bayfit <- tune.iClusterBayes(
  cpus = 5,                         # Matches our Slurm core count
  dt1 = rna_scaled, 
  dt2 = meth_scaled, 
  dt3 = cnv_scaled,
  type = c("gaussian", "gaussian", "gaussian"), 
  K = 1:5,                          # Tests clusters from 2 to 6
  n.burnin = 18000,                 # Standard MCMC burn-in length
  n.draw = 12000,                   # Number of MCMC samples to keep
  prior.gamma = c(0.5, 0.5, 0.5),   # Balanced prior inclusion probability
  sdev = 0.05, 
  thin = 3                          # Reduces autocorrelation
)

cat("Finished model tuning at", as.character(Sys.time()), "\n")

# Save the primary output object safely
output_path <- "/mnt/petasan_ccb/alessandro/SCANB/bayes_fit_results.rds"
saveRDS(bayfit, file = output_path)
cat("Saved results object to:", output_path, "\n")


