# Preprocessing of each omic's dataset specific for each multiomics model
# and saving into ondemand directories

library(minfi)
library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
# library(sesameData)

outdir <- "/mnt/petasan_ccb/alessandro/SCANB/multiomics/input_data/"

# Create the three output subdirectories up front 
dir.create(file.path(outdir, "mofa_inputdata"),     recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(outdir, "icluster_inputdata"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(outdir, "snf_inputdata"),      recursive = TRUE, showWarnings = FALSE)

# RNAseq
rna_data <- readRDS("/mnt/petasan_ccb/alessandro/SCANB/rna_logtransformed.rds")

# Feature selection: top 3000 most variable genes (by MAD)
gene_mads <- apply(rna_data, 1, mad)
ordered_mads <- order(gene_mads, decreasing = TRUE)
top_3000_indices <- ordered_mads[1:3000]
rna_data <- rna_data[top_3000_indices, ]
rna_matrix <- as.matrix(rna_data)



# Methylation
adjusted_data <- readRDS("/mnt/petasan_ccb/alessandro/SCANB/methylation_data/adjusted_data.rds")

# Filtering
ann <- getAnnotation(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
keep_autosomes <- !(ann$chr %in% c("chrX", "chrY"))
keep_cpg <- grepl("^cg", ann$Name)
probes_to_keep <- ann$Name[keep_autosomes & keep_cpg]
probes_filtered <- adjusted_data[rownames(adjusted_data) %in% probes_to_keep, ]
met_filtered <- as.matrix(probes_filtered)




# Enhancer results
enhancers_pairs <- readRDS("/mnt/petasan_ccb/alessandro/SCANB/result_pairs_enhancer.rds")
en_pairs <- enhancers_pairs[order(enhancers_pairs$Pe), ]
top_pairs_en <- en_pairs[en_pairs$Raw.p < 1e-9, ]
top_cpg_en <- unique(top_pairs_en$Probe)

# Promoter results
promoters_pairs <- readRDS("/mnt/petasan_ccb/alessandro/SCANB/result_pairs_promoter.rds")
pr_pairs <- promoters_pairs[order(promoters_pairs$Pe), ]
top_pairs_pr <- pr_pairs[pr_pairs$Raw.p < 1e-9, ]
top_cpg_pr <- unique(top_pairs_pr$Probe)

# Final CpG set
top_cpg_combined <- union(top_cpg_en, top_cpg_pr)
met_matrix_filtered <- met_filtered[rownames(met_filtered) %in% top_cpg_combined, ]

# Transform Beta-values into M-values
met_mvals <- met_matrix_filtered
# prevent +/-Infinity errors
met_mvals[met_mvals == 0] <- 0.001
met_mvals[met_mvals == 1] <- 0.999
# logit transformation to get M-values
met_mvals <- log2(met_mvals / (1 - met_mvals))


# CNV
dna_matrix_filtered <- read.csv("/mnt/petasan_ccb/alessandro/SCANB/dna_matrix_filtered_2900genes.csv",
                                 header = TRUE, row.names = 1)
cnv_log_ratio <- as.matrix(dna_matrix_filtered)   # FIX: cast to matrix for consistency with rna_matrix/met_mvals
# homozygous deletions (0 alleles) to avoid log2(0) = -Inf
cnv_log_ratio[cnv_log_ratio == 0] <- 0.5
# conversion to log2 ratio scale (relative to diploid copy number = 2)
cnv_log_ratio <- log2(cnv_log_ratio / 2)


# Align samples across the three omics
common_samples <- intersect(colnames(rna_matrix), intersect(colnames(met_mvals), colnames(cnv_log_ratio)))
rna_matrix    <- rna_matrix[, common_samples]
met_mvals     <- met_mvals[, common_samples]
cnv_log_ratio <- cnv_log_ratio[, common_samples]


# MOFA-specific preprocessing
# Mean-center the rows (genes/probes) so each feature's average across samples is 0 (scale = FALSE -> do not rescale variance)
rna_cent <- t(scale(t(rna_matrix),    center = TRUE, scale = FALSE))
met_cent <- t(scale(t(met_mvals),     center = TRUE, scale = FALSE))
cnv_cent <- t(scale(t(cnv_log_ratio), center = TRUE, scale = FALSE))

# save MOFA inputs -> outdir/mofa_inputdata/
saveRDS(rna_cent, file = file.path(outdir, "mofa_inputdata", "rna_mofa.rds"))
saveRDS(met_cent, file = file.path(outdir, "mofa_inputdata", "met_mofa.rds"))
saveRDS(cnv_cent, file = file.path(outdir, "mofa_inputdata", "cnv_mofa.rds"))


# iCluster-specific preprocessing
# Samples as rows, features as columns (transpose), then Z-score standardize each feature (column) so every feature contributes equal variance weight
rna_mat  <- t(rna_matrix)
meth_mat <- t(met_mvals)
cnv_mat  <- t(cnv_log_ratio)

# standardize rna_mat/meth_mat/cnv_mat 
rna_scaled  <- scale(rna_mat,  center = TRUE, scale = TRUE)
meth_scaled <- scale(meth_mat, center = TRUE, scale = TRUE)
cnv_scaled  <- scale(cnv_mat,  center = TRUE, scale = TRUE)

# replace any NaNs generated by zero-variance columns
rna_scaled[is.na(rna_scaled)]   <- 0
meth_scaled[is.na(meth_scaled)] <- 0
cnv_scaled[is.na(cnv_scaled)]   <- 0

# save iCluster inputs -> outdir/icluster_inputdata/   
saveRDS(rna_scaled,  file = file.path(outdir, "icluster_inputdata", "rna_icluster.rds"))
saveRDS(meth_scaled, file = file.path(outdir, "icluster_inputdata", "met_icluster.rds"))
saveRDS(cnv_scaled,  file = file.path(outdir, "icluster_inputdata", "cnv_icluster.rds"))


# SNF-specific preprocessing
# Samples as rows, features as columns (transpose only, no centering/scaling)
data_rna  <- t(rna_matrix)
data_meth <- t(met_mvals)
data_cnv  <- t(cnv_log_ratio)

# save SNF inputs -> outdir/snf_inputdata/    
saveRDS(data_rna,  file = file.path(outdir, "snf_inputdata", "rna_snf.rds"))
saveRDS(data_meth, file = file.path(outdir, "snf_inputdata", "met_snf.rds"))
saveRDS(data_cnv,  file = file.path(outdir, "snf_inputdata", "cnv_snf.rds"))
