# Preprocessing of each omic's dataset specific for each multiomics model
# and loading on ondemand directory

output_dir -> "/mnt/petasan_ccb/alessandro/SCANB/"

# RNAseq

rna_data <- read.table("/mnt/petasan_ccb/alessandro/SCANB/rna_logtransformed.tsv", header=TRUE, sep="\t", row.names=1)
# Feature selection
gene_mads <- apply(rna_data, 1, mad)
ordered_mads <- order(gene_mads, decreasing = TRUE)
top_3000_indices <- ordered_mads[1:3000]
rna_data <- rna_data[top_3000_indices, ]
rna_matrix <- as.matrix(rna_data)


## Mehtylation

adjusted_data <- readRDS("/mnt/petasan_ccb/alessandro/SCANB/adjusted_data.rds")
# Filtering
library(minfi)
library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
#library(sesameData)
ann <- getAnnotation(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
keep_autosomes <- !(ann$chr %in% c("chrX", "chrY"))
keep_cpg <- grepl("^cg", ann$Name)
probes_to_keep <- ann$Name[keep_autosomes & keep_cpg]
probes_filtered <- adjusted_data[rownames(adjusted_data) %in% probes_to_keep, ]
met_filtered <- as.matrix(probes_filtered)

# Enhancers results
enhancers_pairs <- readRDS("/mnt/petasan_ccb/alessandro/SCANB/result_pairs_enhancer.rds")
en_pairs <- enhancers_pairs[order(enhancers_pairs$Pe), ]
top_pairs_en <- en_pairs[en_pairs$Raw.p < 1e-9, ]
top_cpg_en <- unique(top_pairs_en$Probe)

# Promoters results
promoters_pairs <- readRDS("/mnt/petasan_ccb/alessandro/SCANB/result_pairs_promoter.rds")
pr_pairs <- promoters_pairs[order(promoters_pairs$Pe), ]
top_pairs_pr <- pr_pairs[pr_pairs$Raw.p < 1e-9, ]
top_cpg_pr <- unique(top_pairs_pr$Probe)

# Final data
top_cpg_combined <- union(top_cpg_en, top_cpg_pr)
met_matrix_filtered <- met_filtered[rownames(met_filtered) %in% top_cpg_combined, ]

# Transform Beta-values into M-values 
met_mvals <- met_matrix_filtered
# to prevent ±Infinity errors
met_mvals[met_mvals == 0] <- 0.001
met_mvals[met_mvals == 1] <- 0.999
# logit transformation to get M-values
met_mvals <- log2(met_mvals / (1 - met_mvals))


# CNV

dna_matrix_filtered <- read.csv("/mnt/petasan_ccb/alessandro/SCANB/dna_matrix_filtered_2900genes.csv", header = TRUE, row.names = 1)
cnv_log_ratio <- dna_matrix_filtered
# homozygous deletions (0 alleles) to avoid log2(0) = -Inf
cnv_log_ratio[cnv_log_ratio == 0] <- 0.5
#  conversion back to log2 scale
cnv_log_ratio <- log2(cnv_log_ratio / 2)

common_samples <- intersect(colnames(rna_matrix), intersect(colnames(met_mvals), colnames(cnv_log_ratio)))
rna_matrix <- rna_matrix[, common_samples]
met_mvals <- met_mvals[, common_samples]
cnv_log_ratio <- cnv_log_ratio[, common_samples]


# MOFA specific preprocessing -> Mean-center the rows (genes) so that each gene's average across samples is 0 (scale = FALSE to not scale the variance)
rna_cent <- t(scale(t(rna_matrix), center = TRUE, scale = FALSE))
met_cent <- t(scale(t(met_mvals), center = TRUE, scale = FALSE))
cnv_cent <- t(scale(t(cnv_log_ratio), center = TRUE, scale = FALSE))

# save MOFA outputs in Mofa directory 

# icluster specific -> transpose
rna_mat <- t(rna_matrix)
meth_mat <- t(met_mvals)
cnv_mat <- t(cnv_log_ratio)

#intersecting samples 
common_samples <- intersect(intersect(rownames(rna_mat), rownames(meth_mat)), rownames(cnv_mat))
# Subset and match the exact row order for all matrices
rna_aligned  <- rna_mat[common_samples, ]
meth_aligned <- meth_mat[common_samples, ]
cnv_aligned  <- cnv_mat[common_samples, ]

# Z-score standardization across features (columns) ensures equal variance weight
rna_scaled  <- scale(rna_aligned, center = TRUE, scale = TRUE)
meth_scaled <- scale(meth_aligned, center = TRUE, scale = TRUE)
cnv_scaled  <- scale(cnv_aligned, center = TRUE, scale = TRUE)

#replace any NaNs generated by zero-variance columns
rna_scaled[is.na(rna_scaled)]   <- 0
meth_scaled[is.na(meth_scaled)] <- 0
cnv_scaled[is.na(cnv_scaled)]   <- 0



# SNF specific preprocessing

# transpose all matrices
data_rna <- t(rna_matrix)      
data_meth <- t(met_mvals)            
data_cnv <- t(cnv_log_ratio)

